### ISSUE TITLE
Adding/ modifying

### ISSUE THREAD

**Issue by SGZ-Creations** [architectury/architectury-example-mod#2]
I'm i required to modify or add a .txt document to run the fabric and java/Curse-forge mods together. i would apricate quick response :)

**Comment by Username404-59** [comment]
What the hell are you trying to do

**Comment by SGZ-Creations** [comment]
Not more than making a server where I use some Fabric and curse-forge mods

**Comment by shedaniel** [comment]
I am not sure what you mean, this is a mod template for architectury, a tool to compile a mod to both fabric and forge. This repo that you are commenting on is mainly mod developer-facing.

I will close this issue now, but you are free to continue discuss here, we will try our best to help.

**Comment by SGZ-Creations** [comment]
Can u just say if this is a mod i put in a mod folder if I want to use forge and fabric mod at once. since I'm confused about waht this dose when u are saying for developer-facing

**Comment by NinjaPhenix** [comment]
Architectury does not let you use fabric and forge mods at the same time.
It allows mod developers to more easisly maintain mods for both fabric and forge.

**Comment by SGZ-Creations** [comment]
Do u know of a mod that dose ?

**Comment by shedaniel** [comment]
No, patchwork kinda did but it doesn't work. Give up on that.

**Comment by SGZ-Creations** [comment]
sadness :(
