### ISSUE TITLE
Question - Priority: Lowish

### ISSUE THREAD

**Issue by BeansBeefBroccoli** [architectury/architectury-example-mod#4]
Am I allowed to change the license on the mod I generated from this to MIT? Thanks. :)

**Comment by MaxNeedsSnacks** [comment]
Yep! This template is CC0, meaning it is a part of the public domain and there are no restrictions as to how you may license the mods you create with it!

**Comment by NinjaPhenix** [comment]
It's public domain, so yes, the goal is to let you do what every you want with it.
