### ISSUE TITLE
Building mod creates weird artifacts

### ISSUE THREAD

**Issue by Terrails** [architectury/architectury-example-mod#6]
Cloning 1.17.1 branch of the example mod and running `gradlew build` creates the following artifacts in both fabric and forge.
![explorer_2021-09-25_436l9P5sV7](https://user-images.githubusercontent.com/8273440/134776310-b511e5f5-cf0b-4cf6-97c8-7d437f2dbdcd.png)
Looking through the files via a jar decompiler shows `dev` artifact containing the classes from its respective module and nothing from the common module, while `dev-shadow` contains both. I'm not sure about `sources` artifacts as they contain basically the same classes from both modules.

**Comment by shedaniel** [comment]
This is fixed recently
