### ISSUE TITLE
Crashes on Forge start 

### ISSUE THREAD

**Issue by natanfudge** [architectury/architectury-example-mod#7]
https://pastebin.com/5ahWVT4k

**Comment by shedaniel** [comment]
The actual error: java.lang.IllegalStateException: Can't get event bus for mod 'examplemod' because it was not registered!

**Comment by natanfudge** [comment]
??? How is this resolved?

**Comment by Username404-59** [comment]
Did you modify [this line](https://github.com/architectury/architectury-example-mod/blob/master/forge/src/main/resources/META-INF/mods.toml#L7)? if yes then that's what causing the issue

**Comment by natanfudge** [comment]
No, i ran it as-is.

**Comment by natanfudge** [comment]
hmm, I can't reproduce this anymore.
